
all:
	cd cgassignment;make
	cd taxoner;make
	cd dbcreator;make

clean:
	rm -f ../bin/taxoner ../bin/cgassignment ../bin/dbcreator
	cd cgassignment; make clean
	cd taxoner; make clean
	cd dbcreator; make clean

