
all:
	cd cgassignment;make
	cd taxoner;make
	cd dbCreator;make

clean:
	rm -f ../bin/taxoner ../bin/cgassignment ../bin/dbcreator
	cd cgassignment; make clean
	cd taxoner; make clean
	cd dbCreator; make clean

