
all:
	cd cgassignment;make
	cd taxoner;make
	cd dbCreator;make
	cd dbCreator2; make
clean:
	rm -f ../bin/taxoner ../bin/cgassignment ../bin/dbcreator ../bin/dbcreator2
	cd cgassignment; make clean
	cd taxoner; make clean
	cd dbCreator; make clean
	cd dbCreator2; make clean

